import turtle

flecha = turtle.Turtle()

def tablero():
  flecha.speed(0)
  flecha.goto(0,-200)  
  flecha.home()  
  flecha.goto(0,200)
  flecha.home()
  flecha.goto(300,0)  
  flecha.home() 
  flecha.goto(-300,0) 
  flecha.home()
  flecha.penup()
  flecha.goto(-100, 0)
  flecha.pendown()
  flecha.goto(-100, 200)
  flecha.penup()
  flecha.home()
  flecha.goto(-100, 0)
  flecha.pendown()
  flecha.goto(-100, -200)
  flecha.penup()
  flecha.home()
  flecha.goto(-200, 0)
  flecha.pendown()
  flecha.goto(-200, 200)
  flecha.penup()
  flecha.home()
  flecha.goto(-200, 0)
  flecha.pendown()
  flecha.goto(-200, -200)
  flecha.penup()
  flecha.home()
  flecha.goto(-300, 0)
  flecha.pendown()
  flecha.goto(-300, 200)
  flecha.penup()
  flecha.home()
  flecha.goto(-300, 0)
  flecha.pendown()
  flecha.goto(-300, -200)
  flecha.penup()
  flecha.home()
  flecha.goto(100, 0)
  flecha.pendown()
  flecha.goto(100, 200)
  flecha.penup()
  flecha.home()
  flecha.goto(100, 0)
  flecha.pendown()
  flecha.goto(100, -200)
  flecha.penup()
  flecha.home()
  flecha.goto(200, 0)
  flecha.pendown()
  flecha.goto(200, 200)
  flecha.penup()
  flecha.home()
  flecha.goto(200, 0)
  flecha.pendown()
  flecha.goto(200, -200)
  flecha.penup()
  flecha.home()
  flecha.goto(300, 0)
  flecha.pendown()
  flecha.goto(300, 200)
  flecha.penup()
  flecha.home()
  flecha.goto(300, 0)
  flecha.pendown()
  flecha.goto(300, -200)
  flecha.penup()
  flecha.home()
  flecha.goto(0, 100)
  flecha.pendown()
  flecha.goto(300,100)  
  flecha.penup()
  flecha.home() 
  flecha.goto(0, 100)
  flecha.pendown()
  flecha.goto(-300,100) 
  flecha.penup()
  flecha.home()
  flecha.pendown()
  flecha.goto(0, -100)
  flecha.pendown()
  flecha.goto(-300,-100) 
  flecha.penup()
  flecha.home()
  flecha.goto(0, -100)
  flecha.pendown()
  flecha.goto(300,-100) 
  flecha.penup()
  flecha.home()
  flecha.goto(-300, 200)
  flecha.pendown()
  flecha.goto(300, 200)
  flecha.penup()
  flecha.goto(300, -200)
  flecha.pendown()
  flecha.goto(-300, -200)
  flecha.penup()
  flecha.home()

def casa(x,y):
  flecha.penup()
  flecha.goto(x + 1,y + 1)
  flecha.color('#ffffff')
  flecha.begin_fill()
  flecha.goto(x + 100, y + 1)
  flecha.goto(x + 100,y + 99)
  flecha.goto(x + 1,y + 99)
  flecha.goto(x + 1,y +1)
  flecha.end_fill()
  flecha.penup()
  flecha.color('#099d4c')
  flecha.begin_fill()
  flecha.goto(x + 1, y + 1)
  flecha.goto(x + 1, y +29)
  flecha.pendown()
  flecha.goto(x + 99, y +29)
  flecha.goto(x + 99, y + 1)
  flecha.penup()
  flecha.end_fill()
  flecha.goto(x + 20, y + 20)
  flecha.pendown()
  flecha.color("#e859c0")
  flecha.begin_fill()
  flecha.forward(60)
  flecha.left(90)
  flecha.forward(40)
  flecha.left(90)
  flecha.forward(60)
  flecha.left(90)
  flecha.forward(40)
  flecha.left(90)
  flecha.end_fill()
  flecha.penup()
  flecha.goto(x + 30, y + 50)
  flecha.pendown()
  flecha.color("#7c94f7")
  flecha.begin_fill()
  flecha.forward(10)
  flecha.left(-90)
  flecha.forward(10)
  flecha.left(-90)
  flecha.forward(10)
  flecha.left(-90)
  flecha.forward(10)
  flecha.left(-90)
  flecha.end_fill()
  flecha.penup()
  flecha.forward(30)
  flecha.pendown()
  flecha.color("#7c94f7")
  flecha.begin_fill()
  flecha.forward(10)
  flecha.left(-90)
  flecha.forward(10)
  flecha.left(-90)
  flecha.forward(10)
  flecha.left(-90)
  flecha.forward(10)
  flecha.left(-90)
  flecha.end_fill()
  flecha.penup()
  flecha.goto(x + 45, y + 20)
  flecha.left(90)
  flecha.pendown()
  flecha.color("#724747")
  flecha.begin_fill()
  flecha.forward(15)
  flecha.left(-90)
  flecha.forward(10)
  flecha.left(-90)
  flecha.forward(15)
  flecha.left(90)
  flecha.end_fill()
  flecha.penup()
  flecha.goto(x + 20, y + 60)
  flecha.pendown()
  flecha.color("#724747")
  flecha.begin_fill()
  flecha.left(30)
  flecha.forward(35)
  flecha.left(-60)
  flecha.forward(35)  
  flecha.left(120)
  flecha.end_fill()
  flecha.penup()
  flecha.goto(x + 70, y + 67)
  flecha.pendown()
  flecha.color("#211a1a")
  flecha.begin_fill()  
  flecha.forward(10)
  flecha.left(90)
  flecha.forward(10) 
  flecha.left(90)
  flecha.forward(5)
  flecha.end_fill()
  flecha.penup()
  flecha.color("#000000")
  flecha.home() 

def bote(x,y):
  flecha.penup()
  flecha.goto(x + 1,y + 1)
  flecha.color('#ffffff')
  flecha.begin_fill()
  flecha.goto(x + 100, y + 1)
  flecha.goto(x + 100,y + 99)
  flecha.goto(x + 1,y + 99)
  flecha.goto(x + 1,y +1)
  flecha.end_fill()
  flecha.penup()
  flecha.color('#1ebdfa')
  flecha.begin_fill()
  flecha.goto(x + 1, y + 30)
  flecha.pendown()
  flecha.goto(x + 99, y + 30)
  flecha.goto(x + 99, y + 1)
  flecha.penup()
  flecha.end_fill()
  flecha.color('#ffbc84')
  flecha.begin_fill()
  flecha.goto(x + 40, y + 20)
  flecha.pendown()
  flecha.forward(20)
  flecha.goto(x + 80, y + 40)
  flecha.left(180)
  flecha.forward(60)
  flecha.goto(x + 40, y + 20)
  flecha.left(180)
  flecha.end_fill()
  flecha.penup()
  flecha.color('#ffbc84')
  flecha.begin_fill()
  flecha.goto(x + 49,y + 40)
  flecha.left(90)
  flecha.pendown()
  flecha.forward(40)
  flecha.left(-90)
  flecha.forward(2)
  flecha.left(-90)
  flecha.forward(40)  
  flecha.penup()
  flecha.end_fill()
  flecha.color('#ff003e')
  flecha.begin_fill()  
  flecha.goto(x + 51, y + 80)
  flecha.pendown()
  flecha.goto(x + 80, y + 70)
  flecha.goto(x + 51, y + 60)
  flecha.end_fill()  
  flecha.penup()
  flecha.color("#000000")
  flecha.home()

def piramide(x,y):
  flecha.penup()
  flecha.goto(x + 1,y + 1)
  flecha.color('#ffffff')
  flecha.begin_fill()
  flecha.goto(x + 100, y + 1)
  flecha.goto(x + 100,y + 99)
  flecha.goto(x + 1,y + 99)
  flecha.goto(x + 1,y +1)
  flecha.end_fill()
  flecha.color('#632e2a')
  flecha.begin_fill()
  flecha.goto(x + 1, y + 30)
  flecha.pendown()
  flecha.goto(x + 99, y + 30)
  flecha.goto(x + 99, y + 1)
  flecha.penup()
  flecha.end_fill()
  flecha.color('#c69a5c')
  flecha.begin_fill()
  flecha.goto(x + 20, y + 30)
  flecha.pendown()
  flecha.goto(x + 40, y + 20)
  flecha.goto(x + 80, y + 30)
  flecha.goto(x + 50, y + 80)
  flecha.goto(x + 20, y + 30)
  flecha.penup()
  flecha.end_fill()
  flecha.color('#826439')
  flecha.goto(x + 50, y + 80)
  flecha.pendown()
  flecha.goto(x + 40, y + 20)
  flecha.penup()
  flecha.goto(x + 30, y + 30)
  flecha.pendown()
  flecha.goto(x + 37, y + 27)
  flecha.penup()
  flecha.color("#000000")
  flecha.home()

def poker(x,y):
  flecha.penup()
  flecha.goto(x + 1,y + 1)
  flecha.color('#ffffff')
  flecha.begin_fill()
  flecha.goto(x + 100, y + 1)
  flecha.goto(x + 100,y + 99)
  flecha.goto(x + 1,y + 99)
  flecha.goto(x + 1,y +1)
  flecha.end_fill()
  flecha.begin_fill()  
  flecha.color('#6c8fff')
  flecha.goto(x + 25, y + 10)
  flecha.pendown()
  flecha.goto(x + 75, y + 10)
  flecha.goto(x + 75, y + 90)
  flecha.goto(x + 25, y + 90)
  flecha.goto(x + 25, y + 10)
  flecha.penup()
  flecha.end_fill()   
  flecha.begin_fill()  
  flecha.color("#c100ff")
  flecha.goto(x + 50, y + 30)
  flecha.pendown()
  flecha.goto(x + 60, y + 50)
  flecha.goto(x + 50, y + 70)
  flecha.goto(x + 40, y + 50)
  flecha.goto(x + 50, y + 30)
  flecha.end_fill()
  flecha.begin_fill()  
  flecha.color("#d962ff")
  flecha.penup()
  flecha.goto(x + 60, y + 25)
  flecha.pendown()
  flecha.goto(x + 65, y + 18)
  flecha.goto(x + 70, y + 25)
  flecha.goto(x + 65, y + 32)
  flecha.goto(x + 60, y + 25)
  flecha.penup()
  flecha.end_fill()  
  flecha.begin_fill()  
  flecha.color("#d962ff")
  flecha.goto(x + 30, y + 75)
  flecha.pendown()
  flecha.goto(x + 35, y + 68)
  flecha.goto(x + 40, y + 75)
  flecha.goto(x + 35, y + 82)
  flecha.goto(x + 30, y + 75)
  flecha.penup()
  flecha.end_fill()  
  flecha.color("#000000")
  flecha.home()

def steve(x,y): #4
  flecha.penup()
  flecha.goto(x + 1,y + 1)
  flecha.color('#ffffff')
  flecha.begin_fill()
  flecha.goto(x + 100, y + 1)
  flecha.goto(x + 100,y + 99)
  flecha.goto(x + 1,y + 99)
  flecha.goto(x + 1,y +1)
  flecha.end_fill()
  flecha.penup()
  flecha.color('#70f96d')
  flecha.begin_fill()
  flecha.goto(x + 1, y + 20)
  flecha.pendown()
  flecha.goto(x + 99, y + 20)
  flecha.goto(x + 99, y + 1)
  flecha.penup()
  flecha.end_fill()
  flecha.color("#4639a4")
  flecha.goto(x + 40, y + 10)
  flecha.begin_fill()
  flecha.pendown()
  flecha.goto(x + 40, y + 40)
  flecha.goto(x + 50, y + 40)
  flecha.goto(x + 50, y + 39)
  flecha.goto(x + 53, y + 39)
  flecha.goto(x + 53, y + 37)
  flecha.goto(x + 56, y + 37)
  flecha.goto(x + 56, y + 35)
  flecha.goto(x + 60, y + 35)
  flecha.goto(x + 60, y + 10)
  flecha.goto(x + 40, y + 10)
  flecha.end_fill()
  flecha.penup()
  flecha.color("#00acaa")
  flecha.begin_fill()
  flecha.goto(x + 40, y + 40)
  flecha.pendown()
  flecha.goto(x + 50, y + 40)
  flecha.goto(x + 50, y + 39)
  flecha.goto(x + 53, y + 39)
  flecha.goto(x + 53, y + 37)
  flecha.goto(x + 56, y + 37)
  flecha.goto(x + 56, y + 35)
  flecha.goto(x + 60, y + 35)
  flecha.goto(x + 60, y + 50)
  flecha.goto(x + 70, y + 50)
  flecha.goto(x + 70, y + 60)
  flecha.goto(x + 30, y + 60)
  flecha.goto(x + 30, y + 50)
  flecha.goto(x + 40, y + 50)
  flecha.goto(x + 40, y + 40)
  flecha.end_fill()
  flecha.penup()
  flecha.color("#ab7d66")
  flecha.begin_fill()
  flecha.goto(x + 60, y + 50)
  flecha.pendown()
  flecha.goto(x + 60, y + 35)
  flecha.goto(x + 70, y + 35)
  flecha.goto(x + 70, y + 50)
  flecha.goto(x + 60, y + 50)
  flecha.penup()
  flecha.end_fill()
  flecha.color("#ab7d66")
  flecha.begin_fill()
  flecha.goto(x + 30, y + 50)
  flecha.pendown()
  flecha.goto(x + 40, y + 50)
  flecha.goto(x + 40, y + 35)
  flecha.goto(x + 30, y + 35)
  flecha.goto(x + 30, y + 50)
  flecha.penup()
  flecha.end_fill()
  flecha.color("#bc8e72")
  flecha.begin_fill()
  flecha.goto(x + 42, y + 60)
  flecha.pendown()
  flecha.goto(x + 42, y + 76)
  flecha.goto(x + 58, y + 76)
  flecha.goto(x + 58, y + 60)
  flecha.goto(x + 42, y + 60)
  flecha.penup()
  flecha.end_fill()
  flecha.color("#2b1e0b")
  flecha.begin_fill()
  flecha.goto(x + 42, y + 70)
  flecha.pendown()
  flecha.goto(x + 44, y + 70)
  flecha.goto(x + 44, y + 72)
  flecha.goto(x + 56, y + 72)
  flecha.goto(x + 56, y + 70)
  flecha.goto(x + 58, y + 70)
  flecha.goto(x + 58, y + 76)
  flecha.goto(x + 42, y + 76)
  flecha.goto(x + 42, y + 70)
  flecha.penup()
  flecha.end_fill()
  flecha.color("#774234")
  flecha.begin_fill()
  flecha.goto(x + 46, y + 60)
  flecha.pendown()
  flecha.goto(x + 54, y + 60)
  flecha.goto(x + 54, y + 64)
  flecha.goto(x + 52, y + 64)
  flecha.goto(x + 52, y + 62)
  flecha.goto(x + 48, y + 62)
  flecha.goto(x + 48, y + 64)
  flecha.goto(x + 46, y + 64)
  flecha.goto(x + 46, y + 60)
  flecha.penup()
  flecha.end_fill()
  flecha.color("#fefefc")
  flecha.begin_fill()
  flecha.goto(x + 44, y + 68)
  flecha.pendown()
  flecha.goto(x + 48, y + 68)
  flecha.goto(x + 48, y + 66)
  flecha.goto(x + 44, y + 66)
  flecha.goto(x + 44, y + 68)
  flecha.penup()
  flecha.end_fill()
  flecha.color("#533d8b")
  flecha.begin_fill()
  flecha.goto(x + 46, y + 68)
  flecha.pendown()
  flecha.goto(x + 48, y + 68)
  flecha.goto(x + 48, y + 66)
  flecha.goto(x + 46, y + 66)
  flecha.goto(x + 46, y + 68)
  flecha.penup()
  flecha.end_fill()
  flecha.color("#fefefc")
  flecha.begin_fill()
  flecha.goto(x + 52, y + 68)
  flecha.pendown()
  flecha.goto(x + 56, y + 68)
  flecha.goto(x + 56, y + 66)
  flecha.goto(x + 52, y + 66)
  flecha.goto(x + 52, y + 68)
  flecha.penup()
  flecha.end_fill()
  flecha.color("#533d8b")
  flecha.begin_fill()
  flecha.goto(x + 52, y + 68)
  flecha.pendown()
  flecha.goto(x + 54, y + 68)
  flecha.goto(x + 54, y + 66)
  flecha.goto(x + 52, y + 66)
  flecha.goto(x + 52, y + 68)
  flecha.penup()
  flecha.end_fill()
  flecha.color("#69412e")
  flecha.begin_fill()
  flecha.goto(x + 48, y + 66)
  flecha.pendown()
  flecha.goto(x + 52, y + 66)
  flecha.goto(x + 52, y + 64)
  flecha.goto(x + 48, y + 64)
  flecha.goto(x + 48, y + 66)
  flecha.penup()
  flecha.end_fill()
  flecha.color("#000000")
  flecha.home()

def llave(x,y):
  flecha.penup()
  flecha.goto(x + 1,y + 1)
  flecha.color('#ffffff')
  flecha.begin_fill()
  flecha.goto(x + 100, y + 1)
  flecha.goto(x + 100,y + 99)
  flecha.goto(x + 1,y + 99)
  flecha.goto(x + 1,y +1)
  flecha.end_fill()
  flecha.goto(x + 50, y + 10)
  flecha.pendown() 
  flecha.color("#4a4f54")
  flecha.begin_fill()
  flecha.goto(x + 40, y + 30)
  flecha.goto(x + 43, y + 35)
  flecha.goto(x + 40, y + 40)
  flecha.goto(x + 43, y + 45)
  flecha.goto(x + 40, y + 50)
  flecha.goto(x + 40, y + 60)
  flecha.goto(x + 30, y + 60)
  flecha.goto(x + 30, y + 90)
  flecha.goto(x + 70, y + 90)
  flecha.goto(x + 70, y + 60)
  flecha.goto(x + 60, y + 60)
  flecha.goto(x + 60, y + 50)
  flecha.goto(x + 55, y + 45)
  flecha.goto(x + 55, y + 45)
  flecha.goto(x + 60, y + 45)
  flecha.goto(x + 60, y + 20)
  flecha.goto(x + 50, y + 10)
  flecha.end_fill()
  flecha.penup()
  flecha.goto(x + 40, y + 80)
  flecha.pendown()
  flecha.begin_fill()
  flecha.color("#ffffff")
  flecha.goto(x + 60, y + 80)
  flecha.goto(x + 60, y + 70)
  flecha.goto(x + 40, y + 70)
  flecha.goto(x + 40, y + 80)
  flecha.end_fill()
  flecha.penup()
  flecha.color("#000000")
  flecha.home()

def cubo3d(x,y):
  flecha.penup()
  flecha.goto(x + 1,y + 1)
  flecha.color('#ffffff')
  flecha.begin_fill()
  flecha.goto(x + 100, y + 1)
  flecha.goto(x + 100,y + 99)
  flecha.goto(x + 1,y + 99)
  flecha.goto(x + 1,y +1)
  flecha.end_fill()
  flecha.color('#6ee8b5')
  flecha.begin_fill()
  flecha.penup()
  flecha.goto(x + 20 ,y + 30)
  flecha.pendown()
  flecha.goto(x + 50 ,y + 20)
  flecha.goto(x + 50 ,y + 30)
  flecha.goto(x + 30 ,y + 40)
  flecha.goto(x + 30 ,y + 60)
  flecha.goto(x + 20 ,y + 70)
  flecha.goto(x + 20 ,y + 30)
  flecha.end_fill()
  flecha.penup()
  flecha.color('#4ba881')
  flecha.begin_fill()
  flecha.goto(x + 20 ,y + 70)
  flecha.pendown()
  flecha.goto(x + 50 ,y + 80)
  flecha.goto(x + 80 ,y + 70)
  flecha.goto(x + 70 ,y + 60)
  flecha.goto(x + 50 ,y + 70)
  flecha.goto(x + 30 ,y + 60)
  flecha.goto(x + 20 ,y + 70)
  flecha.end_fill()
  flecha.penup()
  flecha.color('#317056')
  flecha.begin_fill()
  flecha.goto(x + 80 ,y + 70)
  flecha.pendown()
  flecha.goto(x + 80 ,y + 30)
  flecha.goto(x + 50 ,y + 20)
  flecha.goto(x + 50 ,y + 30)
  flecha.goto(x + 70 ,y + 40)
  flecha.goto(x + 70 ,y + 60)
  flecha.goto(x + 80 ,y + 70)
  flecha.end_fill()
  flecha.penup()
  flecha.color('#85ff7d')
  flecha.begin_fill()
  flecha.goto(x + 30 ,y + 60)
  flecha.pendown()
  flecha.goto(x + 50 ,y + 70)
  flecha.goto(x + 50 ,y + 50)
  flecha.goto(x + 30 ,y + 40)
  flecha.goto(x + 30 ,y + 60)
  flecha.end_fill()
  flecha.penup()
  flecha.color('#54a04e')
  flecha.begin_fill()
  flecha.goto(x + 50 ,y + 70)
  flecha.pendown()
  flecha.goto(x + 70 ,y + 60)
  flecha.goto(x + 70 ,y + 40)
  flecha.goto(x + 50 ,y + 50)
  flecha.goto(x + 50 ,y + 70)
  flecha.end_fill()
  flecha.penup()
  flecha.color('#336c2e')
  flecha.begin_fill()
  flecha.goto(x + 30 ,y + 40)
  flecha.pendown()
  flecha.goto(x + 50 ,y + 50)
  flecha.goto(x + 70 ,y + 40)
  flecha.goto(x + 50 ,y + 30)
  flecha.goto(x + 30 ,y + 40)
  flecha.end_fill()
  flecha.penup()
  flecha.color("#000000")
  flecha.home()

def gatito(x,y): #7
  flecha.penup()
  flecha.goto(x + 1,y + 1)
  flecha.color('#ffffff')
  flecha.begin_fill()
  flecha.goto(x + 100, y + 1)
  flecha.goto(x + 100,y + 99)
  flecha.goto(x + 1,y + 99)
  flecha.goto(x + 1,y +1)
  flecha.end_fill()
  flecha.begin_fill()
  flecha.goto(x + 50, y + 10)
  flecha.pendown()  
  flecha.color("#a86748")
  flecha.goto(x + 70, y + 20)
  flecha.goto(x + 80, y + 50)
  flecha.goto(x + 70, y + 90)
  flecha.goto(x + 60, y + 70)
  flecha.goto(x + 40, y + 70)
  flecha.goto(x + 30, y + 90)
  flecha.goto(x + 20, y + 50)
  flecha.goto(x + 30, y + 20)
  flecha.goto(x + 50, y + 10)
  flecha.penup()
  flecha.end_fill()
  flecha.begin_fill()
  flecha.goto(x + 40, y + 70)
  flecha.pendown()
  flecha.color("#cf9f88")
  flecha.goto(x + 30, y + 20)
  flecha.goto(x + 20, y + 50)
  flecha.goto(x + 40, y + 70)
  flecha.penup()
  flecha.end_fill()
  flecha.begin_fill()
  flecha.color("#cf9f88")
  flecha.goto(x + 60, y + 70)
  flecha.pendown()
  flecha.goto(x + 70, y + 20)
  flecha.goto(x + 80, y + 50)
  flecha.goto(x + 60, y + 70)
  flecha.penup()
  flecha.end_fill()
  flecha.begin_fill()
  flecha.color("#cf9f88")
  flecha.goto(x + 30, y + 20)
  flecha.pendown()
  flecha.goto(x + 45, y + 25)
  flecha.goto(x + 55, y + 25)
  flecha.goto(x + 70, y + 20)
  flecha.goto(x + 50, y + 10)  
  flecha.goto(x + 30, y + 20)
  flecha.penup()
  flecha.end_fill()
  flecha.begin_fill()
  flecha.color("#f5a6c0")
  flecha.goto(x + 45, y + 25)
  flecha.pendown()
  flecha.goto(x + 50, y + 35)
  flecha.goto(x + 55, y + 25)
  flecha.goto(x + 45, y + 25)
  flecha.penup()
  flecha.end_fill()
  flecha.begin_fill()
  flecha.color("#000000")
  flecha.goto(x + 40, y + 50)
  flecha.pendown()
  flecha.goto(x + 45, y + 50)
  flecha.goto(x + 45, y + 40)
  flecha.goto(x + 40, y + 40)
  flecha.goto(x + 40, y + 50)
  flecha.penup()
  flecha.end_fill()
  flecha.begin_fill()
  flecha.color("#000000")
  flecha.goto(x + 60, y + 50)
  flecha.pendown()
  flecha.goto(x + 60, y + 40)
  flecha.goto(x + 55, y + 40)
  flecha.goto(x + 55, y + 50)
  flecha.goto(x + 60, y + 50)
  flecha.penup()
  flecha.end_fill()
  flecha.home()

def bola_abs(x,y): #8
  flecha.penup()
  flecha.goto(x + 1,y + 1)
  flecha.color('#ffffff')
  flecha.begin_fill()
  flecha.goto(x + 100, y + 1)
  flecha.goto(x + 100,y + 99)
  flecha.goto(x + 1,y + 99)
  flecha.goto(x + 1,y +1)
  flecha.end_fill()
  flecha.begin_fill()
  flecha.color("#bbf8ff")
  flecha.goto(x + 50 ,y + 90)
  flecha.goto(x + 75 ,y + 75)
  flecha.goto(x + 90 ,y + 50)
  flecha.goto(x + 75 ,y + 25)
  flecha.goto(x + 50 ,y + 10)
  flecha.goto(x + 25 ,y + 25)
  flecha.goto(x + 10 ,y + 50)
  flecha.goto(x + 25 ,y + 75)
  flecha.goto(x + 50 ,y + 90)
  flecha.penup()
  flecha.end_fill()
  flecha.begin_fill()
  flecha.color("#6cefff")
  flecha.goto(x + 50 ,y + 80)
  flecha.pendown()
  flecha.goto(x + 75 ,y + 75)
  flecha.goto(x + 80 ,y + 50)
  flecha.goto(x + 75 ,y + 25)
  flecha.goto(x + 50 ,y + 20)
  flecha.goto(x + 25 ,y + 25)
  flecha.goto(x + 20 ,y + 50)
  flecha.goto(x + 25 ,y + 75)
  flecha.goto(x + 50 ,y + 80)
  flecha.penup()
  flecha.end_fill()
  flecha.begin_fill()
  flecha.color("#00d1ea")
  flecha.goto(x + 50 ,y + 80)
  flecha.pendown()
  flecha.goto(x + 80 ,y + 50)
  flecha.goto(x + 50 ,y + 20)
  flecha.goto(x + 20 ,y + 50)
  flecha.goto(x + 50 ,y + 80)
  flecha.penup()
  flecha.end_fill()
  flecha.home()

def corona(x,y): #9
  flecha.penup()
  flecha.goto(x + 1,y + 1)
  flecha.color('#ffffff')
  flecha.begin_fill()
  flecha.goto(x + 100, y + 1)
  flecha.goto(x + 100,y + 99)
  flecha.goto(x + 1,y + 99)
  flecha.goto(x + 1,y +1)
  flecha.end_fill()
  flecha.begin_fill()
  flecha.goto(x + 30, y + 20)
  flecha.pendown() 
  flecha.color('#cdc11c')
  flecha.goto(x + 70, y + 20)
  flecha.goto(x + 70, y + 30)
  flecha.goto(x + 30, y + 30)
  flecha.goto(x + 30, y + 20)
  flecha.penup()
  flecha.end_fill()
  flecha.begin_fill()
  flecha.color('#ffee00')
  flecha.goto(x + 30, y + 30)
  flecha.pendown()
  flecha.goto(x + 20, y + 70)
  flecha.goto(x + 40, y + 50)
  flecha.goto(x + 50, y + 80)
  flecha.goto(x + 60, y + 50)
  flecha.goto(x + 80, y + 70)
  flecha.goto(x + 70, y + 30)
  flecha.goto(x + 30, y + 30)
  flecha.end_fill()
  flecha.begin_fill()
  flecha.penup()
  flecha.color('#ff0000')
  flecha.goto(x + 50, y + 60)
  flecha.pendown()
  flecha.goto(x + 55, y + 45)
  flecha.goto(x + 50, y + 30)
  flecha.goto(x + 45, y + 45)
  flecha.goto(x + 50, y + 60)
  flecha.penup()
  flecha.end_fill()
  flecha.color("#000000")
  flecha.home()

def espada(x,y): #10
  flecha.penup()
  flecha.goto(x + 1,y + 1)
  flecha.color('#ffffff')
  flecha.begin_fill()
  flecha.goto(x + 100, y + 1)
  flecha.goto(x + 100,y + 99)
  flecha.goto(x + 1,y + 99)
  flecha.goto(x + 1,y +1)
  flecha.end_fill()
  flecha.begin_fill()
  flecha.color('#1bbe06')
  flecha.goto(x + 90, y + 10)
  flecha.pendown() 
  flecha.goto(x + 90, y + 20)
  flecha.goto(x + 80, y + 20)
  flecha.goto(x + 80, y + 10)
  flecha.goto(x + 90, y + 10)
  flecha.end_fill()
  flecha.penup()
  flecha.begin_fill()
  flecha.color("#88ff79")
  flecha.goto(x + 90, y + 20)
  flecha.pendown()
  flecha.goto(x + 75, y + 35)
  flecha.goto(x + 75, y + 45)
  flecha.goto(x + 80, y + 50)
  flecha.goto(x + 70, y + 60)
  flecha.goto(x + 70, y + 50)
  flecha.goto(x + 50, y + 30)
  flecha.goto(x + 40, y + 30)
  flecha.goto(x + 50, y + 20)
  flecha.goto(x + 55, y + 25)
  flecha.goto(x + 65, y + 25)
  flecha.goto(x + 80, y + 10)
  flecha.goto(x + 80, y + 20)  
  flecha.goto(x + 90, y + 20)
  flecha.penup()
  flecha.end_fill()
  flecha.begin_fill()
  flecha.color("#ed4040")
  flecha.goto(x + 70, y + 30)
  flecha.pendown()
  flecha.goto(x + 70, y + 40)
  flecha.goto(x + 60, y + 40)
  flecha.goto(x + 60, y + 30)
  flecha.goto(x + 70, y + 30)
  flecha.penup()
  flecha.end_fill()
  flecha.color("#000000")
  flecha.goto(x + 65, y + 45)
  flecha.pendown()
  flecha.goto(x + 30, y + 80)
  flecha.goto(x + 10, y + 90)
  flecha.goto(x + 20, y + 70)
  flecha.goto(x + 55, y + 35)
  flecha.penup()
  flecha.goto(x + 60, y + 40)
  flecha.pendown()
  flecha.goto(x + 10, y + 90)
  flecha.penup()
  flecha.color("#000000")
  flecha.home()

def chile(x,y): #11
  flecha.penup()
  flecha.goto(x + 1,y + 1)
  flecha.color('#ffffff')
  flecha.begin_fill()
  flecha.goto(x + 100, y + 1)
  flecha.goto(x + 100,y + 99)
  flecha.goto(x + 1,y + 99)
  flecha.goto(x + 1,y +1)
  flecha.end_fill()
  flecha.begin_fill()
  flecha.goto(x + 10, y + 20)
  flecha.pendown()  
  flecha.color("#ff0000")
  flecha.goto(x + 90, y + 20)
  flecha.goto(x + 90, y + 80)
  flecha.goto(x + 10, y + 80)
  flecha.goto(x + 10, y + 20)
  flecha.penup()
  flecha.end_fill()
  flecha.begin_fill()
  flecha.color("#ffffff")
  flecha.goto(x + 10, y + 50)
  flecha.pendown()
  flecha.goto(x + 90, y + 50)
  flecha.goto(x + 90, y + 80)
  flecha.goto(x + 10, y + 80)
  flecha.goto(x + 10, y + 50)
  flecha.penup()
  flecha.end_fill()
  flecha.begin_fill()
  flecha.color("#0011ff")
  flecha.goto(x + 40, y + 80)
  flecha.pendown()
  flecha.goto(x + 40, y + 50)
  flecha.goto(x + 10, y + 50)
  flecha.goto(x + 10, y + 80)
  flecha.goto(x + 40, y + 80)
  flecha.penup()
  flecha.end_fill()
  flecha.begin_fill()
  flecha.color("#ffffff")
  flecha.goto(x + 25, y + 80)
  flecha.pendown()
  flecha.goto(x + 30, y + 70)
  flecha.goto(x + 40, y + 70)
  flecha.goto(x + 30, y + 65)
  flecha.goto(x + 35, y + 55)
  flecha.goto(x + 25, y + 60)
  flecha.goto(x + 15, y + 55)
  flecha.goto(x + 20, y + 65)
  flecha.goto(x + 10, y + 70)
  flecha.goto(x + 20, y + 70)
  flecha.goto(x + 25, y + 80)
  flecha.penup()
  flecha.end_fill()
  flecha.goto(x + 10, y + 20)
  flecha.pendown()  
  flecha.color("#000000")
  flecha.goto(x + 90, y + 20)
  flecha.goto(x + 90, y + 80)
  flecha.goto(x + 10, y + 80)
  flecha.goto(x + 10, y + 20)
  flecha.penup()
  flecha.color("#000000")
  flecha.home()
